### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by kersteinperez** [kersteinperez/RbbrDckApp#1]
@jasonseminara @williamfshaw @amcooper @zhenpanda

I like the idea but I'm not married to how to accomplish it. Basically, I really liked that cheer-ups homework we did when Dennis was here, and I also enjoy the articles you post. I thought it would be cool to put them together since at week 11, I could really use something like this. I figured making a website that generates something random onclick might be too light for a final? Definitely doable but I'm not sure that it meets expectations. I figured putting the thought into a mobile app and having to learn swift would up the ante. I am totally open to suggestions (including, but not limited to: telling me that this is crazy and I should come back to earth and just do a to-do app or blog type project within my given skill set). Thank you!

Orrrrrrrr can I use cordova and build it in straight HTML, CSS, JS?

**Comment by jasonseminara** [comment]
DENIED.
